# ==============================================================================
# wg0.conf - Configuración del servidor WireGuard
# ==============================================================================

# Server can be my PC or Router ZTE at my house: 
# Router ZTE: 

[Interface]
Address = 10.200.0.1/24
ListenPort = 51820
PrivateKey = QIDwaTnyKF9bdIgqvEllgHg8lH9kLDn7+J/PaiXqvXY=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp7s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o enp7s0 -j MASQUERADE


# Cliente 1: (movil sergio - 10.200.0.2)
[Peer]
PublicKey = EfOjSzHSVqSxGMI3BLZMJnfidZ334S8dfEQyLBvjkwg=
AllowedIPs = 10.200.0.2/32

# Cliente 2: (movil sergio - 10.200.0.3)
[Peer]
PublicKey = X2BYORWuZixNAag7gFwyd0k7gwgATKll74DZrvCJvWo=
AllowedIPs = 10.200.0.3/32

# Cliente 3: SmartTV - 10.200.0.4)
[Peer]
PublicKey = ZzscGIusgiKr4NpWx5l2QYPy7Tc3HInmDtYmyzuZEjQ=
AllowedIPs = 10.200.0.4/32

# Cliente 4: movil Luisa - 10.200.0.5)
[Peer]
PublicKey = PxErbb5gFjA3hwrUJqnjyH5e61gMyNsSB+fR56kZLnI=
AllowedIPs = 10.200.0.5/32
